### ISSUE TITLE
Atributos Piece

### ISSUE THREAD

**Issue by gfzabarino** [frcutngrupo9/sigmaproject#5]
Hola @danielrhelmfelt, che por que hay una unidad de medida para cada dimensión de Piece? No tendría que ser una sola unidad de medida para toda la pieza? tipo m3 o algo así?

**Comment by frcutngrupo9** [comment]
Le agregue las unidades de medida a Piece, porque aveces el largo esta en metros, y el ancho y el espesor en cm.
