### ISSUE TITLE
Tipos Double

### ISSUE THREAD

**Issue by gfzabarino** [frcutngrupo9/sigmaproject#6]
@danielrhelmfelt , creo que sería mejor usar `BigDecimal` en vez de `Double`. `BigDecimal` tiene la ventaja de no tener errores de precisión, sobre todo a la hora de hacer operaciones. `Double` va acarreando errores de precisión a medida que se va operando, y en consecuencia varios resultados terminan quedando inexactos / mal.

Hay algún motivo para usar `Double`? Si no, lo puedo cambiar a `BigDecimal`?

**Comment by frcutngrupo9** [comment]
Sip, no hay drama, cambia nomas a BigDecimal. 
Yo lo había puesto BigDecimal solo para medir la plata. Como no es necesario hacer cálculos complicados con la cantidades  o tamaños, los puse en double, pero mejor cambiar todo a BigDecimal, ya que es mas preciso y de paso queda todo unificado, no hay impedimentos en el código.
